const supabase_Url='https://kvzcrsreatymwjxdtkrq.supabase.co'
const supabase_Key='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2emNyc3JlYXR5bXdqeGR0a3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzOTY0MzUsImV4cCI6MjA3OTk3MjQzNX0.eMWKh3RM_CiU8Xx9I5vnDEiPYr1gb4ouSdZStg2BC5M'

const {createClient} = supabase
let client = createClient(supabase_Url,supabase_Key)
console.log(createClient,client)
